### ISSUE TITLE
Space Ship out of bounds

### ISSUE THREAD

**Issue by AyaanGH** [jefftheprogrammer/space-invaders-game#1]
When the spaceship is on the extreme right, it is out of bounds   #@jefftheprogrammer
![image](https://cloud.githubusercontent.com/assets/25395404/22390915/dc40add2-e4e5-11e6-92a3-ac28f8b6a7ed.png)

**Comment by jefftheprogrammer** [comment]
I will fix it tomorrow.

**Comment by AyaanGH** [comment]
lol ok

**Comment by jefftheprogrammer** [comment]
I've fixed the ship out of bounds bug.

Since the sprite is 40px wide, the sprite should stop moving when x = 760. But instead it now stops at 755. I am not too sure why, but it isn't significant bug so I won't bother fixing it right now.
